### ISSUE TITLE
トップの説明の画像と文章がバランスよく配置されない

### ISSUE THREAD

**Issue by whooku** [whooku/band_birthday#13]

**Comment by kojitaniguchi** [comment]
```css
/* step1 */
.content_how_step1{
    width: 100%;
    display: flex;
    justify-content: space-around;
    align-items: center;
}

img.photo_how_step1{
    width: 40%;
}

h4.text_how_step1{
    margin: 70px 0px;
    float: right;
}

/* step2 */
.content_how_step2{
    width: 100%;
    display: flex;
    justify-content: space-around;
    align-items: center;
}

h4.text_how_step2{
    margin: 70px 0px;
    float: right;
}

img.photo_how_step2{
    width: 40%;
}

/* step3 */
.content_how_step3{
    width: 100%;
    display: flex;
    justify-content: space-around;
    align-items: center;
}

img.photo_how_step3{
    width: 40%;
}


h4.text_how_step3{
    margin: 70px 0px;
    float: right;
}

/* step4 */
.content_how_step4{
    width: 100%;
    display: flex;
    justify-content: space-around;
    align-items: center;
}

h4.text_how_step4{
    margin: 70px 0px;
    float: right;
}

img.photo_how_step4{
    width: 40%;
}

```
