### ISSUE TITLE
about の フォントサイズ

### ISSUE THREAD

**Issue by kojitaniguchi** [whooku/band_birthday#26]

**Comment by kojitaniguchi** [comment]
まず、CSSを整理する

```css
/* about部分 */
.about {
    text-align: center;
    padding: 60px;
}

.about1 {
    margin: 30px;
}

.about1 h3 {
    font-size: 14px;
    font-weight: bold;
}

.about1 p {
    font-size: 10px;
    font-weight: bold;
    letter-spacing: 3px;
}

.about2 {
    margin: 30px;
}

.about2 p {
    font-size: 15px;
    font-weight: bold;
    letter-spacing: 3px;
}
```
