### ISSUE TITLE
斜め背景

### ISSUE THREAD

**Issue by kojitaniguchi** [whooku/band_birthday#9]
参考記事
https://theorthodoxworks.com/web-design/slanting-background-css/

**Comment by kojitaniguchi** [comment]
### 右下がり
[![Image from Gyazo](https://i.gyazo.com/f54e00ce725c84ba817274d9ef7cebe3.png)](https://gyazo.com/f54e00ce725c84ba817274d9ef7cebe3)
```html
<section class="contents">
    <div class="contents_inner">
      　happy-musician
    </div>
</section>
```
```css
.contents {
    position: relative;
    overflow: hidden;
    margin: 10% 0;
    padding: 80px 0;
}

.contents:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 120%;
    height: 80%;
    margin: 3% -10% 0;
    background: #011931;
    -webkit-transform-origin: left center;
    -ms-transform-origin: left center;
    transform-origin: left center;
    -webkit-transform: rotate(3deg);
    -ms-transform: rotate(3deg);
    transform: rotate(3deg);
    z-index: -1;
}

.contents_inner {
    box-sizing: boder-box;
    width: 100%;
    max-width: 640px;
    height: 100%;
    margin: 0 auto;
    padding: 100px 10px 120px;
    color: #fff;
    text-align: center;
}

```

### 右上がり
[![Image from Gyazo](https://i.gyazo.com/cd507ad5ce769e9bc1b3b54d18181545.png)](https://gyazo.com/cd507ad5ce769e9bc1b3b54d18181545)
他のところは共通で、 `.contents:before` だけを変える
```css
.contents:before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 120%;
  height: 80%;
  margin: 2% -10% 0;
  background: #011931;
  -webkit-transform-origin: right center;
  -ms-transform-origin: right center;
  transform-origin: right center;
  -webkit-transform: rotate(-3deg);
  -ms-transform: rotate(-3deg);
  transform: rotate(-3deg);
  z-index: -1;
}
```
